networks:
  team07:
    external: true

services:
  presentation-web-frontend:
    build: .
    container_name: presentation-web-frontend
    image: presentation-web-frontend
    restart: unless-stopped
    ports:
      - ${PRESENTATION_FRONTEND_HOST_PORT:-8000}:3000
    networks:
      - team07
